spring:
  application:
    name: smart-home-server
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/smart_home}
    username: ${DATABASE_USERNAME:smarthome}
    password: ${DATABASE_PASSWORD:smarthome}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080
